# Generated by Django 4.1.5 on 2024-11-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.CharField(max_length=255)),
                ('time_casa', models.CharField(max_length=255)),
                ('time_visitante', models.CharField(max_length=255)),
                ('horario', models.TimeField()),
                ('local_transmissao', models.CharField(max_length=255)),
                ('link_transmissao', models.URLField()),
            ],
        ),
    ]
