# Generated by Django 5.1.3 on 2024-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuscaOdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaBrasileirao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('jogos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('derrotas', models.IntegerField()),
            ],
        ),
    ]
